#!/usr/bin/env python3
"""Regenerate the derived files: per-level VOCABULARY.md and README indexes.

These files are generated — edit the stories, then run this. Run with --check
to fail if anything on disk is out of date (used by CI).
"""

from __future__ import annotations

import argparse
import os
import sys

import lexicon as lx

GENERATED_NOTE = "<!-- Generated by tools/build.py — do not edit by hand. -->"


def vocabulary_page(level: str, stories: list) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        f"# {level} Vocabulary Log",
        "",
        "Every word taught at this level, in the order a reader meets it. The",
        "validator uses this ordering to reject a story that re-teaches a word or",
        "teaches one that already appeared earlier, so this page is a record, not a",
        "checklist to maintain by hand.",
        "",
        "| # | Story | New words | Cumulative |",
        "|---|-------|-----------|------------|",
    ]
    total = 0
    for index, story in enumerate(stories, start=1):
        total += len(story["glossary"])
        name = os.path.basename(story["path"])
        words = ", ".join(word for word, _ in story["glossary"])
        lines.append(f"| {index:02d} | [{story['title']}](./{name}) | {words} | {total} |")

    lines += ["", f"**{total} words taught across {len(stories)} stories.**", "", "## Glossary", ""]
    entries = sorted(
        ((word, definition, os.path.basename(story["path"]), story["title"])
         for story in stories for word, definition in story["glossary"]),
        key=lambda item: item[0],
    )
    lines += ["| Word | Meaning | Taught in |", "|------|---------|-----------|"]
    for word, definition, filename, title in entries:
        lines.append(f"| {word} | {definition} | [{title}](./{filename}) |")
    return "\n".join(lines) + "\n"


LEVEL_BLURB = {
    "A1": ("Beginner", "Short sentences, present and past simple, and the everyday vocabulary of daily routines, family, shopping and work."),
    "A2": ("Elementary", "Longer narratives, a full range of past forms, future and comparatives, covering practical adult situations."),
    "B1": ("Intermediate", "A wider range of tenses, opinions and topics involving work, travel and personal experience."),
    "B2": ("Upper Intermediate", "Complex sentence structures, idiomatic expressions, and abstract or specialized topics."),
    "C1": ("Advanced", "Nuanced language, implicit meaning, and complex narrative structures on a wide range of topics."),
    "C2": ("Proficiency", "Near-native fluency, subtle stylistic and cultural nuance, and sophisticated vocabulary."),
}


def level_readme(level: str, stories: list, config: dict) -> str:
    name, blurb = LEVEL_BLURB[level]
    cfg = config["levels"][level]
    lines = [
        GENERATED_NOTE,
        "",
        f"# {level} — {name}",
        "",
        blurb,
        "",
        f"- **Prose length:** {cfg['word_count']['min']}-{cfg['word_count']['max']} words",
        f"- **New words per story:** up to {cfg['new_word_budget']}",
        f"- **Vocabulary ceiling:** `wordlists/` up to and including `{level}.txt`",
        "",
    ]
    if not stories:
        lines += ["No stories yet at this level.", ""]
        return "\n".join(lines)

    lines += [
        "## Stories",
        "",
        "| # | Story | Words | New | Topic |",
        "|---|-------|-------|-----|-------|",
    ]
    for index, story in enumerate(stories, start=1):
        name_ = os.path.basename(story["path"])
        topic = story["meta"].get("topic", "")
        words = lx.count_words(story["prose"])
        lines.append(f"| {index:02d} | [{story['title']}](./{name_}) | {words} | {len(story['glossary'])} | {topic} |")

    cast = []
    for story in stories:
        for character in story["meta"].get("characters", []):
            if character not in cast:
                cast.append(character)
    if cast:
        lines += [
            "",
            "## Recurring cast",
            "",
            "Stories at this level share characters, so the reader builds context",
            "instead of meeting a new set of names in every text.",
            "",
            ", ".join(cast) + ".",
        ]

    lines += ["", f"Vocabulary taught at this level: [VOCABULARY.md](./VOCABULARY.md).", ""]
    return "\n".join(lines)


def root_readme(config: dict, all_stories: dict) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        "# English Stories",
        "",
        "Graded short stories for adult English learners (roughly 20-45 years old),",
        "organized by CEFR level. Every story is checked against a machine-readable",
        "level contract: a pinned vocabulary ceiling, a new-word budget, a grammar",
        "inventory, and US English throughout.",
        "",
        "## Levels",
        "",
        "| Level | Description | Stories | Words taught |",
        "|-------|-------------|---------|--------------|",
    ]
    for level in config["order"]:
        name, _ = LEVEL_BLURB[level]
        stories = all_stories.get(level, [])
        taught = sum(len(s["glossary"]) for s in stories)
        lines.append(f"| [{level}](./{level}) | {name} | {len(stories)} | {taught} |")

    lines += [
        "",
        "## Read them on the web",
        "",
        "The stories are published as a static site at",
        "**https://juananmch.github.io/english-stories/**, where the words each story",
        "teaches are marked in the text and show their meaning when you tap them.",
        "The site is rebuilt and deployed on every push to `main`.",
        "",
        "## How this works",
        "",
        "- [`CLAUDE.md`](./CLAUDE.md) — the working instructions, loaded automatically by Claude Code.",
        "- [`SPECIFICATIONS.md`](./SPECIFICATIONS.md) — the rules every story follows.",
        "- [`PROMPT.md`](./PROMPT.md) — the canonical prompt for generating a new story.",
        "- [`config/levels.json`](./config/levels.json) — word ranges, new-word budgets and grammar inventory per level.",
        "- [`wordlists/`](./wordlists) — the vocabulary a reader is assumed to know at each level.",
        "- [`tools/validate.py`](./tools/validate.py) — enforces all of the above.",
        "",
        "## Checking and building",
        "",
        "```sh",
        "python3 tools/validate.py -v     # check every story against its level",
        "python3 tools/build.py           # regenerate VOCABULARY.md and the indexes",
        "python3 tools/build.py --check   # fail if generated files are stale",
        "python3 tools/site.py            # build the web version into _site/",
        "```",
        "",
        "Everything runs on a plain Python 3 install with no dependencies, and runs in",
        "CI on every push. To preview the site locally:",
        "",
        "```sh",
        "python3 tools/site.py && python3 -m http.server --directory _site",
        "```",
        "",
    ]
    return "\n".join(lines)


def write(path: str, content: str, check: bool, stale: list) -> None:
    existing = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            existing = fh.read()
    if existing == content:
        return
    if check:
        stale.append(os.path.relpath(path, lx.ROOT))
        return
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {os.path.relpath(path, lx.ROOT)}")


def fix_meta(config: dict) -> None:
    """Recompute word_count and new_words in each story's front matter.

    These are derived values; keeping them by hand guarantees they drift.
    """
    import re

    for level in config["order"]:
        for path in lx.story_files(level):
            story = lx.load_story(path)
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
            updated = text
            for field, value in (
                ("word_count", lx.count_words(story["prose"])),
                ("new_words", len(story["glossary"])),
            ):
                pattern = re.compile(rf"^({field}:\s*)(\d+)\s*$", re.MULTILINE)
                if pattern.search(updated):
                    updated = pattern.sub(rf"\g<1>{value}", updated, count=1)
            if updated != text:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(updated)
                print(f"updated front matter in {story['rel']}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    parser.add_argument("--fix-meta", action="store_true", help="recompute word_count and new_words in front matter")
    args = parser.parse_args()

    config = lx.load_config()
    stale: list = []
    all_stories = {}

    if args.fix_meta:
        fix_meta(config)

    for level in config["order"]:
        stories = [lx.load_story(p) for p in lx.story_files(level)]
        all_stories[level] = stories
        level_dir = os.path.join(lx.ROOT, level)
        if not os.path.isdir(level_dir):
            continue
        write(os.path.join(level_dir, "README.md"), level_readme(level, stories, config), args.check, stale)
        if stories:
            write(os.path.join(level_dir, "VOCABULARY.md"), vocabulary_page(level, stories), args.check, stale)

    write(os.path.join(lx.ROOT, "README.md"), root_readme(config, all_stories), args.check, stale)

    if stale:
        print("Generated files are out of date. Run: python3 tools/build.py")
        for path in stale:
            print(f"  {path}")
        return 1
    if args.check:
        print("Generated files are up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
